# **23.frobenius norm**

In [ ]:
#1. menggunakan numpy, pytoch dan tensorflow buatlah matrix ukuran 3x3 lalu hitung nilai frobenius norm
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,67]])
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 67]])

In [ ]:
np.linalg.norm(X)

np.float64(68.5054742338158)

In [ ]:
import torch
x_pt = torch.tensor([[1,2,3],[4,5,6],[7,8,6]], dtype=float)
x_pt

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 6.]], dtype=torch.float64)

In [ ]:
torch.norm(x_pt)

tensor(15.4919, dtype=torch.float64)

In [ ]:
import tensorflow as tf
x_tf = tf.Variable([[1,2,3],[4,5,6],[7,8,67]], dtype=float)
x_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 67.]], dtype=float32)>

In [ ]:
tf.norm(x_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=68.50547790527344>

# **24.Matrix Multiplication**

1.Buat Matrix A Dengan Ukuran 2x3 Dan Vector B

Matriks dan vector dengan numpy:

In [34]:
#buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
import numpy as np
A = np.array([[76,67,89], [87,90,84]])
A

array([[76, 67, 89],
       [87, 90, 84]])

In [37]:
b = np.array([[34],
              [45],
              [70]])
b

array([[34],
       [45],
       [70]])

Dengan pytorch:

In [35]:
#buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
import torch
A_pt = torch.tensor([[76,67,89], [87,90,84]], dtype=float)
A_pt

tensor([[76., 67., 89.],
        [87., 90., 84.]], dtype=torch.float64)

In [40]:
b_pt = torch.tensor([[34],
                     [45],
                     [70]], dtype=float)
b_pt

tensor([[34.],
        [45.],
        [70.]], dtype=torch.float64)

Dengan tensorflow:

In [ ]:
#buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
import tensorflow as tf
A_tf = tf.Variable([[76,67,89], [87,90,84]], dtype=float)
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[76., 67., 89.],
       [87., 90., 84.]], dtype=float32)>

In [ ]:
b_tf = tf.Variable([[34],
                    [45],
                    [70]], dtype=float)
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[34.],
       [45.],
       [70.]], dtype=float32)>

2.Tampilkan Ukuran Matrix A Dan Vector B

In [ ]:
A.shape

(2, 3)

In [ ]:
b.shape

(3, 1)

3.Kalikan Matrix A Dengan Vector B

In [ ]:

np.dot(A, b)

array([[11829],
       [12888]])

4.Buat Matrix B Dengan Ukuran 3x3 Menggunakan Numpy

In [45]:

B = np.array([[76,67,89], [87,90,84], [56,42,12]])
B

array([[76, 67, 89],
       [87, 90, 84],
       [56, 42, 12]])

buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch:

In [ ]:
B_pt = torch.tensor([[76,67,89], [87,90,84], [56,42,12]], dtype=float)
B_pt

tensor([[76., 67., 89.],
        [87., 90., 84.],
        [56., 42., 12.]], dtype=torch.float64)

buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow:

In [ ]:
B_tf = tf.Variable([[76,67,89], [87,90,84], [56,42,12]], dtype=float)
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[76., 67., 89.],
       [87., 90., 84.],
       [56., 42., 12.]], dtype=float32)>

5.Kalikan Matrix A Dengan Matrix B

In [ ]:
np.dot(A,B)

array([[16589, 14860, 13460],
       [19146, 17457, 16311]])

kalikan matrix A_pt dengan matrix B_pt:

In [ ]:
A_pt @ B_pt

tensor([[16589., 14860., 13460.],
        [19146., 17457., 16311.]], dtype=torch.float64)

kalikan matrix A_tf dengan matrix B_tf

In [ ]:
tf.linalg.matvec(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[18186., 20118.],
       [20118., 22725.],
       [ 8138.,  9660.]], dtype=float32)>

6.buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

In [46]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("matriks AB:\n",AB)
print("matriks BA:\n",BA)
#Kesimpulan AB tidak sama dengan BA

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

# **25.Symmetric and Identity Matrices**

In [ ]:
import numpy as np

In [ ]:
# buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
X_sym = np.array([[1, 0, 8], [0, 7, 6], [8, 6, 9]])
X_sym

array([[1, 0, 8],
       [0, 7, 6],
       [8, 6, 9]])

In [ ]:
# menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
import torch
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [ ]:
# menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor([[9],
                     [7],
                     [1],
                     [8]])
b_pt

tensor([[9],
        [7],
        [1],
        [8]])

In [ ]:
# kalikan matrix I dengan vector b_pt
torch.matmul(I, b_pt)

tensor([[9],
        [7],
        [1],
        [8]])

# **26.Matrix Multiplication**

In [ ]:
# lakukan perhitungan soal excercise menggunakan collab
import torch

1

In [ ]:
M_q = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
M_q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
V_q = torch.tensor([[-1],
                    [1],
                    [-2]])
V_q

tensor([[-1],
        [ 1],
        [-2]])

In [ ]:
torch.matmul(M_q, V_q)

tensor([[ -3],
        [ -9],
        [-15]])

2

In [ ]:
I3 = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I3

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [ ]:
torch.matmul(I3, V_q)

tensor([[-1],
        [ 1],
        [-2]])

3

In [ ]:
T_q = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
T_q

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [ ]:
torch.matmul(M_q, T_q)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])

### Matrix Inversion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[10, 3], [8, 9]])
X

array([[10,  3],
       [ 8,  9]])

In [ ]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[ 0.13636364, -0.04545455],
       [-0.12121212,  0.15151515]])

As a quick aside, let's prove that $X^{-1}X = I_n$ as per the slides:

In [ ]:
#kalikan X dengan Xinv menggunakan numpy
np.dot(Xinv, X)

array([[1.0000000e+00, 6.9388939e-18],
       [0.0000000e+00, 1.0000000e+00]])





selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch
$$ 4b + 2c = 4 $$
$$ -5b - 3c = -7 $$


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import tensorflow as tf

In [ ]:
#Dengan Numpy
A = np.array([[4,2], [-5,-3]])
B = np.array([[4,-7]])
A
A_inv = np.linalg.inv(A)
C = A_inv.dot(B.T)
C

array([[-1.],
       [ 4.]])

In [ ]:
#Dengan Pytorch
x = torch.tensor([[4.0, 2.0],[-5.0, -3.0]] )

y = torch.tensor([[4.0], [-7.0]])
x_inv = torch.linalg.inv(x)

solution = x_inv @ y

print(solution)

tensor([[-1.],
        [ 4.]])


In [ ]:
#dengan Tensorflow
a = tf.Variable([[4.0, 2.0],[-5.0, -3.0]] )
b = tf.Variable([[4.0], [-7.0]])
a_inv = tf.linalg.inv(a)
solution = a_inv @ b
print(solution)

tf.Tensor(
[[-0.9999995]
 [ 3.999999 ]], shape=(2, 1), dtype=float32)
