# 6.**skalar**

In [ ]:
#1 buat variabel skalar x dan simpan suatu nilai skalar
#tampilkan tipe data dari x
x = 84
x



84

In [ ]:
#tampilkan tipe data dari x
type(x)

int

In [ ]:
#buat variabel skalar y dan simpan suatu nilai skalar
y = 34
y

34

In [ ]:
#taampilkan tipe data dari y
type(y)

int

In [ ]:
#jumlahkan x+y
py_sum = x + y
py_sum

118

In [ ]:
#buat variabel bernama x_float dan simpan suatu nilai desimal
x_float = 0.84
x_float

0.84

In [ ]:
#jumlahkan x_float dengan y
py_sum = x_float + y
py_sum

34.84

In [ ]:
#tampilkan tipe data dari x_float
type(x_float)

float

In [ ]:
#2 lakukan tahapan pada soal satu mengunakan tesor flow

In [ ]:
import tensorflow as tf
x_tf = tf.Variable(0.84, dtype=float)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.8399999737739563>

In [ ]:
x_tf.shape

TensorShape([])

In [ ]:
y_tf = tf.Variable(84,0, dtype = float)
y_tf

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=84.0>

In [ ]:
y_tf.shape

TensorShape([])

In [ ]:
x_tf + y_tf


<tf.Tensor: shape=(), dtype=float32, numpy=84.83999633789062>

In [ ]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=float32, numpy=84.83999633789062>

In [ ]:
tf_sum.numpy()

np.float32(84.84)

In [ ]:
type(tf_sum.numpy())

numpy.float32

In [ ]:
tf_sum.numpy()
tf_sum

<tf.Tensor: shape=(), dtype=float32, numpy=84.83999633789062>

In [ ]:
type(tf_sum.numpy())

numpy.float32

In [ ]:
x_float = np.array(0.84)
x_float

array(0.84)

In [ ]:
#3 lakukan tahapan pada soal 1 dengan menggunakan pytorch

In [ ]:
import torch
x_pt = torch.tensor(84)
x_pt

tensor(84)

In [ ]:
x_pt.shape

torch.Size([])

In [ ]:
y = torch.tensor(34)
y

tensor(34)

In [ ]:
py_sum = x_pt + y
py_sum

tensor(118)

In [ ]:
x_float = torch.tensor(0.84)
x_float

tensor(0.8400)

In [ ]:
py_sum = x_float + y
py_sum

tensor(34.8400)

# 7.Vector and vector transpositions

In [ ]:
#1. buat vector dengan ukuran 3x1
import numpy as np
x = np.array([[84],
             [79],
             [89]])
x

array([[84],
       [79],
       [89]])

In [ ]:
#hitung panjang vector x
len(x)

3

In [ ]:
#tampilkan ukuran vector x
x.shape

(3, 1)

In [ ]:
#tampilkan tipe data x
type(x)

numpy.ndarray

In [ ]:
#akses elemen pertama x
x[0]

array([84])

In [ ]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

In [ ]:
#2. lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[84, 79, 89]])

In [ ]:
#tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [ ]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[84],
              [79],
              [89]])
y_t = y.T
y_t

array([[84, 79, 89]])

In [ ]:
#tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

In [ ]:
#3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

#Pytorch
x_pt = torch.tensor([[84],
                     [79],
                     [89]])
x_pt

tensor([[84],
        [79],
        [89]])

In [ ]:
x_pt.shape

torch.Size([1, 3])

In [ ]:
x_pt = torch.tensor([[84],
                    [79],
                     [89]])
x_pt = x_pt.T
x_pt

tensor([[84, 79, 89]])

In [ ]:
#Tensor Flow
x_tf = tf.Variable([[84],
                   [79],
                   [89]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[84],
       [79],
       [89]], dtype=int32)>

In [ ]:
x_tf.shape

TensorShape([3, 1])

In [ ]:
x_tf = tf.Variable([[84],
                   [79],
                   [89]])
x_tf = tf.transpose(x_tf)
x_tf

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[84, 79, 89]], dtype=int32)>

# **8.Norms and Unit Vector**

In [ ]:
#buat vector x dengan ukuran 3x1
import numpy as np
x = np.array([[84],
             [79],
             [89]])
x

array([[84],
       [79],
       [89]])

In [ ]:
#hitung nilai L2 norm dari vector x
np.linalg.norm(x)

np.float64(145.6639969244288)

In [ ]:
#buat vector v dengan elemen (3,4)
v = np.array([[84],[89],[90],[67],
              [75],[78],[73],[71],
              [68],[64],[69],[67]])
v

array([[84],
       [89],
       [90],
       [67],
       [75],
       [78],
       [73],
       [71],
       [68],
       [64],
       [69],
       [67]])

In [ ]:
#hitung nilai L2 norm dari vector v
np.linalg.norm(v)

np.float64(260.0288445538302)

In [ ]:
#tampilkan unit vector dari vector v
unit_vector = v / np.linalg.norm(v)
unit_vector

array([[0.32304108],
       [0.34226972],
       [0.34611545],
       [0.25766372],
       [0.28842954],
       [0.29996672],
       [0.28073809],
       [0.27304663],
       [0.26150945],
       [0.24612654],
       [0.26535518],
       [0.25766372]])

In [ ]:
#hitung panjang unit vector dari vector v
len = np.linalg.norm(v)
len

np.float64(260.0288445538302)

# **9.Basis, Orthogonal, and Orthonormal Vectors**

In [ ]:
#buat vector i dengan elemen (1,0) dan vector j dengan elemen (0,1)
i = np.array([1,0])
i

array([1, 0])

In [ ]:
j = np.array([0,1])
j

array([0, 1])

In [ ]:
#buktikan bahwa vector i dan vector j itu orthogonal
np.dot(i, j)

np.int64(0)

In [ ]:
#Bagaimana dengan v=(1,2) dan w=(2,-1), apakah juga orthogonal?
v = np.array([1,2])
w = np.array([2,-1])
np.dot(v, w)

np.int64(0)

# **10.Matrix Tensor**

In [ ]:
#buat matrix X berukuran 2x3 menggunakan numpy
import numpy as np
x = np.array([[84,89,67], [90,54,87]])
x

array([[84, 89, 67],
       [90, 54, 87]])

In [ ]:
#tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [ ]:
#tampilkan seluruh elemen dari kolom pertama dari matrix X
x[0]

array([84, 89, 67])

In [ ]:
#tampilkan seluruh elemen dari baris kedua dari matrix X
x[1]

array([90, 54, 87])

In [ ]:
#ulangi soal nomor 1 menggunakan pytorch
import torch
x_pt = torch.tensor([[84,89,67], [90,54,87]])
x_pt

tensor([[84, 89, 67],
        [90, 54, 87]])

In [ ]:
x_pt.shape

torch.Size([2, 3])

In [ ]:
x_pt[0]

tensor([84, 89, 67])

In [ ]:
x_pt[1]

tensor([90, 54, 87])

In [ ]:
#ulangi soal nomor 1 menggunakan tensorflow
x_tf = tf.Variable([[84,89,67], [90,54,87]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[84, 89, 67],
       [90, 54, 87]], dtype=int32)>

In [ ]:
x_tf.shape

TensorShape([2, 3])

In [ ]:
x_tf[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([84, 89, 67], dtype=int32)>

In [ ]:
x_tf[1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([90, 54, 87], dtype=int32)>

# **11.Generic Tensor Notation**

In [ ]:
#1 jelaskan tentang perintah ini
images_pt = torch.zeros([32, 28, 28, 3])
images_pt
#tensor ini digunakan untuk membuat sebuah tensor di pytorch yang bernilai 0 biasa digunakan untuk mereprentasikan batch gambar.
#tensor ini memiliki 4 dimensi (rank 4 tensor).dimulai dari batch size (jumlah gambar yang akan diproses) = 32, length (tinggi gambar) = 28, width (lebar gambar) = 28, channels (warna Rgb: merah,hijau,biru) = 3


tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

# **12.Exercises on Algebra Data Structures**

In [ ]:
#1. selesaikan soal berikut
x = np.array([[25],
              [2],
              [-3],
              [-25]])
x = x.T
x

array([[ 25,   2,  -3, -25]])